name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        GOARCH=amd64 GOOS=darwin go build -o download/darwin/fofago-darwin main.go
        cp config.yaml /home/runner/work/fofago/fofago/download/darwin/
        tar -zcvf /download/darwin.tar.gz /download/darwin
        GOARCH=amd64 GOOS=darwin go build -o download/linux/fofago-linux main.go
        cp config.yaml /home/runner/work/fofago/fofago/download/linux/
        tar -zcvf /download/linux.tar.gz /download/linux
        GOARCH=amd64 GOOS=darwin go build -o download/windows/fofago-windows main.go
        cp config.yaml /home/runner/work/fofago/fofago/download/windows/
        tar -zcvf /download/windows.tar.gz /download/windows

    - name: UPX
      if: github.ref == 'refs/heads/master'
      run: |
       upx -9 bin/*

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: dev
        files: download/
